mkdir include
mkdir include/caffe
mkdir include/caffe/util
mkdir src
mkdir src/caffe
mkdir src/caffe/layers
mkdir src/caffe/proto
mkdir src/caffe/util
mkdir tools
cp ../caffe-fast-rcnn/include/caffe/blob.hpp include/caffe/blob.hpp
cp ../caffe-fast-rcnn/include/caffe/common.hpp  include/caffe/common.hpp 
cp ../caffe-fast-rcnn/include/caffe/common_layers.hpp include/caffe/common_layers.hpp
cp ../caffe-fast-rcnn/include/caffe/fast_rcnn_layers.hpp include/caffe/fast_rcnn_layers.hpp
cp ../caffe-fast-rcnn/include/caffe/filler.hpp include/caffe/filler.hpp
cp ../caffe-fast-rcnn/include/caffe/layer.hpp include/caffe/layer.hpp
cp ../caffe-fast-rcnn/include/caffe/layer_factory.hpp include/caffe/layer_factory.hpp
cp ../caffe-fast-rcnn/include/caffe/loss_layers.hpp include/caffe/loss_layers.hpp
cp ../caffe-fast-rcnn/include/caffe/net.hpp include/caffe/net.hpp
cp ../caffe-fast-rcnn/include/caffe/neuron_layers.hpp include/caffe/neuron_layers.hpp
cp ../caffe-fast-rcnn/include/caffe/syncedmem.hpp include/caffe/syncedmem.hpp
cp ../caffe-fast-rcnn/include/caffe/vision_layers.hpp include/caffe/vision_layers.hpp
cp ../caffe-fast-rcnn/include/caffe/util/cudnn.hpp include/caffe/util/cudnn.hpp
cp ../caffe-fast-rcnn/include/caffe/util/device_alternate.hpp include/caffe/util/device_alternate.hpp
cp ../caffe-fast-rcnn/include/caffe/util/gpu_nms.hpp include/caffe/util/gpu_nms.hpp
cp ../caffe-fast-rcnn/include/caffe/util/gpu_util.cuh include/caffe/util/gpu_util.cuh
cp ../caffe-fast-rcnn/include/caffe/util/im2col.hpp include/caffe/util/im2col.hpp
cp ../caffe-fast-rcnn/include/caffe/util/insert_splits.hpp include/caffe/util/insert_splits.hpp
cp ../caffe-fast-rcnn/include/caffe/util/io.hpp include/caffe/util/io.hpp
cp ../caffe-fast-rcnn/include/caffe/util/math_functions.hpp include/caffe/util/math_functions.hpp
cp ../caffe-fast-rcnn/include/caffe/util/mkl_alternate.hpp include/caffe/util/mkl_alternate.hpp
cp ../caffe-fast-rcnn/include/caffe/util/rng.hpp include/caffe/util/rng.hpp
cp ../caffe-fast-rcnn/include/caffe/util/upgrade_proto.hpp include/caffe/util/upgrade_proto.hpp
cp ../caffe-fast-rcnn/src/caffe/blob.cpp src/caffe/blob.cpp
cp ../caffe-fast-rcnn/src/caffe/common.cpp src/caffe/common.cpp
cp ../caffe-fast-rcnn/src/caffe/layer.cpp src/caffe/layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layer_factory.cpp src/caffe/layer_factory.cpp
cp ../caffe-fast-rcnn/src/caffe/net.cpp src/caffe/net.cpp
cp ../caffe-fast-rcnn/src/caffe/syncedmem.cpp src/caffe/syncedmem.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/absval_layer.cpp src/caffe/layers/absval_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/absval_layer.cu src/caffe/layers/absval_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/accuracy_layer.cpp src/caffe/layers/accuracy_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/argmax_layer.cpp src/caffe/layers/argmax_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/base_conv_layer.cpp src/caffe/layers/base_conv_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/batch_norm_layer.cpp src/caffe/layers/batch_norm_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/batch_norm_layer.cu src/caffe/layers/batch_norm_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/bnll_layer.cpp src/caffe/layers/bnll_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/bnll_layer.cu src/caffe/layers/bnll_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/concat_layer.cpp src/caffe/layers/concat_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/concat_layer.cu src/caffe/layers/concat_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/conv_layer.cpp src/caffe/layers/conv_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/conv_layer.cu src/caffe/layers/conv_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_conv_layer.cpp src/caffe/layers/cudnn_conv_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_conv_layer.cu src/caffe/layers/cudnn_conv_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_pooling_layer.cpp src/caffe/layers/cudnn_pooling_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_pooling_layer.cu src/caffe/layers/cudnn_pooling_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_relu_layer.cpp src/caffe/layers/cudnn_relu_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_relu_layer.cu src/caffe/layers/cudnn_relu_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_sigmoid_layer.cpp src/caffe/layers/cudnn_sigmoid_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_sigmoid_layer.cu src/caffe/layers/cudnn_sigmoid_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_softmax_layer.cpp src/caffe/layers/cudnn_softmax_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_softmax_layer.cu src/caffe/layers/cudnn_softmax_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_tanh_layer.cpp src/caffe/layers/cudnn_tanh_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/cudnn_tanh_layer.cu src/caffe/layers/cudnn_tanh_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/deconv_layer.cpp src/caffe/layers/deconv_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/deconv_layer.cu src/caffe/layers/deconv_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/dropout_layer.cpp src/caffe/layers/dropout_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/dropout_layer.cu src/caffe/layers/dropout_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/eltwise_layer.cpp src/caffe/layers/eltwise_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/eltwise_layer.cu src/caffe/layers/eltwise_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/embed_layer.cpp src/caffe/layers/embed_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/embed_layer.cu src/caffe/layers/embed_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/exp_layer.cpp src/caffe/layers/exp_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/exp_layer.cu src/caffe/layers/exp_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/filter_layer.cpp src/caffe/layers/filter_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/filter_layer.cu src/caffe/layers/filter_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/flatten_layer.cpp src/caffe/layers/flatten_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/im2col_layer.cpp src/caffe/layers/im2col_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/im2col_layer.cu src/caffe/layers/im2col_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/inner_product_layer.cpp src/caffe/layers/inner_product_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/inner_product_layer.cu src/caffe/layers/inner_product_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/log_layer.cpp src/caffe/layers/log_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/log_layer.cu src/caffe/layers/log_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/lrn_layer.cpp src/caffe/layers/lrn_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/lrn_layer.cu src/caffe/layers/lrn_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/mvn_layer.cpp src/caffe/layers/mvn_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/mvn_layer.cu src/caffe/layers/mvn_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/neuron_layer.cpp src/caffe/layers/neuron_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/pooling_layer.cpp src/caffe/layers/pooling_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/pooling_layer.cu src/caffe/layers/pooling_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/power_layer.cpp src/caffe/layers/power_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/power_layer.cu src/caffe/layers/power_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/precision_layer.cpp src/caffe/layers/precision_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/precision_layer.cu src/caffe/layers/precision_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/prelu_layer.cpp src/caffe/layers/prelu_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/prelu_layer.cu src/caffe/layers/prelu_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/proposal_layer.cpp src/caffe/layers/proposal_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/reduction_layer.cpp src/caffe/layers/reduction_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/reduction_layer.cu src/caffe/layers/reduction_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/relu_layer.cpp src/caffe/layers/relu_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/relu_layer.cu src/caffe/layers/relu_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/reshape_layer.cpp src/caffe/layers/reshape_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/roi_pooling_layer.cpp src/caffe/layers/roi_pooling_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/roi_pooling_layer.cu src/caffe/layers/roi_pooling_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/sigmoid_layer.cpp src/caffe/layers/sigmoid_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/sigmoid_layer.cu src/caffe/layers/sigmoid_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/silence_layer.cpp src/caffe/layers/silence_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/silence_layer.cu src/caffe/layers/silence_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/slice_layer.cpp src/caffe/layers/slice_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/slice_layer.cu src/caffe/layers/slice_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/softmax_layer.cpp src/caffe/layers/softmax_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/softmax_layer.cu src/caffe/layers/softmax_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/split_layer.cpp src/caffe/layers/split_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/split_layer.cu src/caffe/layers/split_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/spp_layer.cpp src/caffe/layers/spp_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/tanh_layer.cpp src/caffe/layers/tanh_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/tanh_layer.cu src/caffe/layers/tanh_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/threshold_layer.cpp src/caffe/layers/threshold_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/threshold_layer.cu src/caffe/layers/threshold_layer.cu
cp ../caffe-fast-rcnn/src/caffe/layers/tile_layer.cpp src/caffe/layers/tile_layer.cpp
cp ../caffe-fast-rcnn/src/caffe/layers/tile_layer.cu src/caffe/layers/tile_layer.cu
cp ../caffe-fast-rcnn/src/caffe/proto/caffe.proto src/caffe/proto/caffe.proto
cp ../caffe-fast-rcnn/src/caffe/util/cudnn.cpp src/caffe/util/cudnn.cpp
cp ../caffe-fast-rcnn/src/caffe/util/im2col.cpp src/caffe/util/im2col.cpp
cp ../caffe-fast-rcnn/src/caffe/util/im2col.cu src/caffe/util/im2col.cu
cp ../caffe-fast-rcnn/src/caffe/util/insert_splits.cpp src/caffe/util/insert_splits.cpp
cp ../caffe-fast-rcnn/src/caffe/util/io.cpp src/caffe/util/io.cpp
cp ../caffe-fast-rcnn/src/caffe/util/math_functions.cpp src/caffe/util/math_functions.cpp
cp ../caffe-fast-rcnn/src/caffe/util/math_functions.cu src/caffe/util/math_functions.cu
cp ../caffe-fast-rcnn/src/caffe/util/nms_kernel.cu src/caffe/util/nms_kernel.cu
cp ../caffe-fast-rcnn/src/caffe/util/upgrade_proto.cpp src/caffe/util/upgrade_proto.cpp
cp ../caffe-fast-rcnn/tools/faster-rcnn.cpp tools/faster-rcnn.cpp
